baseURL = "https://fsharpforfunandprofit.com"
languageCode = "en-us"
title = "F# for Fun and Profit"
description = "This site shows you ways that F# can help in day-to-day development of mainstream commercial business software"
theme = "hugo-geekdoc"

ignoreFiles = [ "\\.fsx$" ]

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  disqus = "fforfunandprofit"
  GeekdocLogo = "favicon-128x128-blue-on-white.png"
  GeekdocMenuBundle = true
  GeekdocAnchor = true

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    style = "pygments"
    tabWidth = 4